# Generated by Django 4.2.7 on 2023-12-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('before', '0002_demo_contact_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
