# Generated by Django 4.2.7 on 2023-12-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('before', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rollno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('rollno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='before.rollno')),
                ('skills', models.ManyToManyField(to='before.skill')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='before.teacher')),
            ],
        ),
    ]
